---
- name: Include ubuntu file if operating system is ubuntu
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  
- name: Include redhat when the operating system is redhat
  include: redhat.yml
  when: ansible_distribution == 'RedHat'
  
- name: Include Amazon when the operating system is redhat
  include: amazon.yml
  when: ansible_distribution == 'Amazon'